// <auto-generated />
namespace AwkwardPresentationBackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removed_name_from_presentationModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removed_name_from_presentationModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201803160939275_removed_name_from_presentationModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
